# Generated by Django 5.1.1 on 2024-10-22 03:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_productoperation'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductOperationTypes',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='productoperation',
            name='operation',
        ),
        migrations.AddField(
            model_name='productoperation',
            name='operation_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.productoperationtypes'),
        ),
    ]
