# Generated by Django 5.1.1 on 2024-10-23 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_productoperationtypes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productoperation',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
