# Generated by Django 5.1.1 on 2024-11-01 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_product_move_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='strequest',
            name='photo_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='strequest',
            name='retouch_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
