# Generated by Django 5.1.1 on 2024-11-08 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_orderproduct_accepted_orderproduct_accepted_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='OrderNumber',
            field=models.BigIntegerField(null=True, unique=True),
        ),
    ]
