# Generated by Django 5.1.1 on 2024-11-20 08:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0012_alter_order_ordernumber'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserURLs',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('income_url', models.CharField(blank=True, max_length=255, null=True)),
                ('outcome_url', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
