# Generated by Django 5.1.1 on 2024-11-28 08:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_strequesthistoryoperations_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('IP', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PhotoStatus',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='strequestproduct',
            name='photos_link',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='strequestproduct',
            name='photo_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.photostatus'),
        ),
    ]
