# Generated by Django 5.1.1 on 2024-12-02 00:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_camera_photostatus_strequestproduct_photos_link_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RetouchRequestStatus',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='RetouchRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RequestNumber', models.BigIntegerField(unique=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('retouch_date', models.DateTimeField(blank=True, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('retoucher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retouch_requests', to=settings.AUTH_USER_MODEL)),
                ('status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.retouchrequeststatus')),
            ],
        ),
        migrations.CreateModel(
            name='RetouchRequestProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('retouch_link', models.TextField(blank=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.product')),
                ('retouch_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request', to='core.retouchrequest')),
                ('retouch_status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.retouchstatus')),
            ],
        ),
        migrations.CreateModel(
            name='ShootingToRetouchLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('retouch_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='linked_to_shooting', to='core.retouchrequest')),
                ('shooting_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='linked_to_retouch', to='core.strequest')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Telegram Username')),
                ('telegram_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='Telegram ID')),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True, verbose_name='Phone Number')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Date of Birth')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
