# Generated by Django 5.1.1 on 2024-12-20 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_product_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='strequestproduct',
            name='OnRetouch',
            field=models.BooleanField(default=False, verbose_name='OnRetouch'),
        ),
    ]
