# Generated by Django 5.1.1 on 2024-12-20 14:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_strequestproduct_onretouch'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='STRequestPhotoTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_date', models.DateTimeField(blank=True, null=True)),
                ('st_request_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photo_times', to='core.strequestproduct')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='st_request_photo_times', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['photo_date'],
            },
        ),
    ]
