# Generated by Django 5.1.1 on 2024-12-20 23:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_strequestphototime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='retouchrequestproduct',
            name='product',
        ),
        migrations.AddField(
            model_name='retouchrequestproduct',
            name='st_request_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='retouch_requests', to='core.strequestproduct'),
        ),
        migrations.AlterField(
            model_name='retouchrequestproduct',
            name='retouch_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retouch_products', to='core.retouchrequest'),
        ),
    ]
