# Generated by Django 5.1.1 on 2024-12-21 00:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_remove_retouchrequestproduct_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retouchrequest',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.retouchrequeststatus'),
        ),
    ]
