# Generated by Django 5.1.1 on 2024-12-26 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_alter_retouchrequest_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blocked_Shops',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('shop_id', models.CharField(max_length=255)),
            ],
        ),
    ]
