# Generated by Django 5.1.1 on 2025-01-16 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_blocked_shops'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='accept_date_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='blocked_shops',
            name='shop_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
