# Generated by Django 5.1.1 on 2025-01-31 12:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_nofoto'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Blocked_Barcode',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('barcode', models.CharField(max_length=13, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='strequest',
            name='assistant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='strequest',
            name='assistant_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
