# Generated by Django 5.1.1 on 2025-02-18 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_blocked_barcode_strequest_assistant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productoperation',
            name='photographer_comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productoperation',
            name='photos_link',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='blocked_barcode',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
