# Generated by Django 5.1.1 on 2025-02-28 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_productoperation_photographer_comment_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['OrderNumber']},
        ),
    ]
